from singer_sdk import typing as th

balance_report_schema = th.PropertiesList(
    th.Property("automatic_payout_effective_at", th.DateTimeType),
    th.Property("automatic_payout_id", th.StringType),
    th.Property("available_on_utc", th.DateTimeType),
    th.Property("balance_transaction_id", th.StringType),
    th.Property("card_address_city", th.StringType),
    th.Property("card_address_country", th.StringType),
    th.Property("card_address_line1", th.StringType),
    th.Property("card_address_line2", th.StringType),
    th.Property("card_address_postal_code", th.StringType),
    th.Property("card_address_state", th.StringType),
    th.Property("card_brand", th.StringType),
    th.Property("card_country", th.StringType),
    th.Property("card_funding", th.StringType),
    th.Property("charge_created_utc", th.DateTimeType),
    th.Property("charge_id", th.StringType),
    th.Property("connected_account_country", th.StringType),
    th.Property("connected_account_direct_charge_id", th.StringType),
    th.Property("connected_account_id", th.StringType),
    th.Property("connected_account_name", th.StringType),
    th.Property("created_utc", th.DateTimeType),
    th.Property("currency", th.StringType),
    th.Property("customer_address_city", th.StringType),
    th.Property("customer_address_country", th.StringType),
    th.Property("customer_address_line1", th.StringType),
    th.Property("customer_address_line2", th.StringType),
    th.Property("customer_address_postal_code", th.StringType),
    th.Property("customer_address_state", th.StringType),
    th.Property("customer_description", th.StringType),
    th.Property("customer_email", th.StringType),
    th.Property("customer_facing_amount", th.StringType),
    th.Property("customer_facing_currency", th.StringType),
    th.Property("customer_id", th.StringType),
    th.Property("customer_name", th.StringType),
    th.Property("customer_shipping_address_city", th.StringType),
    th.Property("customer_shipping_address_country", th.StringType),
    th.Property("customer_shipping_address_line1", th.StringType),
    th.Property("customer_shipping_address_line2", th.StringType),
    th.Property("customer_shipping_address_postal_code", th.StringType),
    th.Property("customer_shipping_address_state", th.StringType),
    th.Property("description", th.StringType),
    th.Property("dispute_reason", th.StringType),
    th.Property("fee", th.StringType),
    th.Property("gross", th.StringType),
    th.Property("invoice_id", th.StringType),
    th.Property("invoice_number", th.StringType),
    th.Property("is_link", th.StringType),
    th.Property("net", th.StringType),
    th.Property("payment_intent_id", th.StringType),
    th.Property("payment_metadata[key]", th.CustomType({"type": ["object", "string"]})),
    th.Property("payment_method_type", th.StringType),
    th.Property("refund_metadata[key]", th.CustomType({"type": ["object", "string"]})),
    th.Property("regulatory_tag", th.StringType),
    th.Property("reporting_category", th.StringType),
    th.Property("shipping_address_city", th.StringType),
    th.Property("shipping_address_country", th.StringType),
    th.Property("shipping_address_line1", th.StringType),
    th.Property("shipping_address_line2", th.StringType),
    th.Property("shipping_address_postal_code", th.StringType),
    th.Property("shipping_address_state", th.StringType),
    th.Property("source_id", th.StringType),
    th.Property("statement_descriptor", th.StringType),
    th.Property("subscription_id", th.StringType),
    th.Property("trace_id", th.StringType),
    th.Property("trace_id_status", th.StringType),
    th.Property(
        "transfer_metadata[key]", th.CustomType({"type": ["object", "string"]})
    ),
).to_dict()
