from singer_sdk import typing as th

tax_report_schema = th.PropertiesList(
    th.Property("country_code", th.StringType),
    th.Property(
        "credit_note_metadata[key]", th.CustomType({"type": ["object", "string"]})
    ),
    th.Property("currency", th.StringType),
    th.Property("customer_tax_id", th.StringType),
    th.Property("destination_resolved_address_country", th.StringType),
    th.Property("destination_resolved_address_state", th.StringType),
    th.Property("filing_currency", th.StringType),
    th.Property("filing_exchange_rate", th.StringType),
    th.Property("filing_non_taxable_amount", th.StringType),
    th.Property("filing_tax_amount", th.StringType),
    th.Property("filing_taxable_amount", th.StringType),
    th.Property("filing_total", th.StringType),
    th.Property("id", th.StringType),
    th.Property("invoice_metadata[key]", th.CustomType({"type": ["object", "string"]})),
    th.Property("jurisdiction_level", th.StringType),
    th.Property("jurisdiction_name", th.StringType),
    th.Property("line_item_id", th.StringType),
    th.Property("non_taxable_amount", th.StringType),
    th.Property("origin_resolved_address_country", th.StringType),
    th.Property("origin_resolved_address_state", th.StringType),
    th.Property("quantity", th.StringType),
    th.Property("quantity_decimal", th.StringType),
    th.Property("refund_metadata[key]", th.CustomType({"type": ["object", "string"]})),
    th.Property("state_code", th.StringType),
    th.Property("subtotal", th.StringType),
    th.Property("tax_amount", th.StringType),
    th.Property("tax_code", th.StringType),
    th.Property("tax_date", th.DateTimeType),
    th.Property("tax_name", th.StringType),
    th.Property("tax_rate", th.StringType),
    th.Property(
        "tax_transaction_metadata[key]", th.CustomType({"type": ["object", "string"]})
    ),
    th.Property("taxability", th.StringType),
    th.Property("taxability_reason", th.StringType),
    th.Property("taxable_amount", th.StringType),
    th.Property("total", th.StringType),
    th.Property("transaction_date", th.DateTimeType),
    th.Property("type", th.StringType),
).to_dict()
